---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# STAT1378 - Assignment 2, Question 2

## Multiserver Package
<!-- badges: start -->
<!-- badges: end -->

The goal of this project is to create a package "Multiserver" that can generate length of time for customers in line at the bank.

The package takes into account "predetermined factors"; the arrival time and length of the service in conjunction with how many bank tellers are working to produce a final result of how long a customer would be waiting in line. 


## Attempted Tasks:

* Correct R package structure
* Appropriate documentation
* Implement `testthat`
* Use `Git` and `GitHub` correctly
* Implemented `tibble`
* Added provided dataset with documentation. 
* Attempted to create a `Github Pages` site see [here](https://mq-stat1378.github.io/assignment2-question2-caitlinapcar/) 
  - I had initially created a page using my "personal" git (i.e the one that isn't connected to this unit) but it wasn't working and somehow I created another one that seemed to be okay but it's not in the list of files within this project if that makes sense! 😄
 

